baseURL = 'https://james-pickett.github.io/gamblebaybirds'
languageCode = 'en-us'
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "Gamble Bay Birds"
    name = "Default User"
    avatar = "/img/default_avatar.png"
