name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-go@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - run: "cd ./postgen && go run ."

      - name: Build
        run: hugo --minify

      - run: "git add -A && git commit -m 'automated commit after content update' && git push"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
